
services:
  backend:
    build: .
    image: sanchit044/vow-backend:latest
    container_name: vow-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - vow-network 

  mongodb:
    image: mongo:6.0
    container_name: vow-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - vow-network

  redis:
    image: redis:7.0
    container_name: vow-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - vow-network


volumes:
  mongo_data:

networks:
  vow-network: